baseURL = "https://octopusflow.github.io/"
languageCode = "en-us"
title = "Octopusflow site"

theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/octopusflow/"
weight = 10

